name: Check for XML Duplicates

on:
  pull_request:
    paths:
      - '**/*.xml'

jobs:
  check-xml-duplicates:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install xmltodict

    - name: Find changed XML files
      id: find_files
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.xml$' || echo '')"

    - name: Check for duplicates in XML files
      if: steps.find_files.outputs.files != ''
      run: |
        python ./.github/check_duplicates.py ${{ steps.find_files.outputs.files }}
